bl_info = {
    "name": "OpenBVE CSV Import/Export (generic)",
    "author": "Generated by Copilot",
    "version": (0, 1),
    "blender": (2, 80, 0),
    "location": "File > Import-Export",
    "description": "Import and export generic CSVs with X,Y,Z coordinates (adaptable to OpenBVE CSVs).",
    "category": "Import-Export",
}

import bpy
import csv
import os
from bpy_extras.io_utils import ImportHelper, ExportHelper
from bpy.props import StringProperty, BoolProperty, EnumProperty, IntProperty, FloatProperty


# Helper to create an empty at location
def create_empty(name, location, parent=None):
    empty = bpy.data.objects.new(name, None)
    empty.empty_display_type = 'PLAIN_AXES'
    empty.location = location
    bpy.context.collection.objects.link(empty)
    if parent:
        empty.parent = parent
    return empty


class ImportOpenBVECSV(bpy.types.Operator, ImportHelper):
    bl_idname = "import_scene.openbve_csv"
    bl_label = "Import OpenBVE CSV"
    bl_options = {'PRESET', 'UNDO'}

    filename_ext = ".csv"
    filter_glob: StringProperty(default="*.csv", options={'HIDDEN'})

    delimiter: StringProperty(
        name="Delimiter",
        default=",",
        description="CSV delimiter character"
    )
    has_header: BoolProperty(
        name="File has header",
        default=True,
    )
    # When header present: use these as field names
    field_x: StringProperty(name="X field", default="x")
    field_y: StringProperty(name="Y field", default="y")
    field_z: StringProperty(name="Z field", default="z")
    field_name: StringProperty(name="Name field", default="name")
    # When no header: use indices
    idx_x: IntProperty(name="X index", default=0, min=0)
    idx_y: IntProperty(name="Y index", default=1, min=0)
    idx_z: IntProperty(name="Z index", default=2, min=0)
    idx_name: IntProperty(name="Name index", default=0, min=0)

    create_objects: EnumProperty(
        name="Create as",
        items=[
            ('EMPTY', "Empty", "Create empties at coordinates"),
            ('MESH', "Mesh (Vertices)", "Create a mesh with vertices at coordinates"),
        ],
        default='EMPTY'
    )

    def execute(self, context):
        path = self.filepath
        if not os.path.exists(path):
            self.report({'ERROR'}, f"File not found: {path}")
            return {'CANCELLED'}

        points = []

        try:
            with open(path, newline='', encoding='utf-8') as csvfile:
                if self.has_header:
                    reader = csv.DictReader(csvfile, delimiter=self.delimiter)
                    for row in reader:
                        try:
                            x = float(row.get(self.field_x, 0))
                            y = float(row.get(self.field_y, 0))
                            z = float(row.get(self.field_z, 0))
                            name = row.get(self.field_name, "") or ""
                            points.append((name, (x, y, z)))
                        except Exception:
                            # skip bad row
                            continue
                else:
                    reader = csv.reader(csvfile, delimiter=self.delimiter)
                    for row in reader:
                        if len(row) == 0:
                            continue
                        try:
                            x = float(row[self.idx_x])
                            y = float(row[self.idx_y])
                            z = float(row[self.idx_z])
                            name = row[self.idx_name] if self.idx_name < len(row) else ""
                            points.append((name, (x, y, z)))
                        except Exception:
                            continue
        except Exception as e:
            self.report({'ERROR'}, f"Error reading CSV: {e}")
            return {'CANCELLED'}

        if len(points) == 0:
            self.report({'WARNING'}, "No points found in CSV.")
            return {'FINISHED'}

        if self.create_objects == 'EMPTY':
            parent = None
            # create an empty parent to hold imported points
            parent = bpy.data.objects.new("OpenBVE_CSV_Import", None)
            parent.empty_display_type = 'ARROWS'
            bpy.context.collection.objects.link(parent)
            for name, loc in points:
                nm = name if name else "pt"
                create_empty(nm, loc, parent=parent)
        else:
            # create mesh with vertices
            mesh = bpy.data.meshes.new("OpenBVE_CSV_Mesh")
            mesh_obj = bpy.data.objects.new("OpenBVE_CSV_MeshObj", mesh)
            bpy.context.collection.objects.link(mesh_obj)
            verts = [p[1] for p in points]
            edges = []
            faces = []
            mesh.from_pydata(verts, edges, faces)
            mesh.update()

            # name vertices if possible via vertex groups -> use custom properties on object for mapping
            for i, (name, _) in enumerate(points):
                if name:
                    # store mapping: vertex_index -> name
                    mesh_obj[f"vtx_{i}_name"] = name

        self.report({'INFO'}, f"Imported {len(points)} points.")
        return {'FINISHED'}


class ExportOpenBVECSV(bpy.types.Operator, ExportHelper):
    bl_idname = "export_scene.openbve_csv"
    bl_label = "Export OpenBVE CSV"

    filename_ext = ".csv"
    filter_glob: StringProperty(default="*.csv", options={'HIDDEN'})

    delimiter: StringProperty(
        name="Delimiter",
        default=",",
        description="CSV delimiter character"
    )
    include_header: BoolProperty(
        name="Include header",
        default=True
    )
    field_name: StringProperty(name="Name field", default="name")
    field_x: StringProperty(name="X field", default="x")
    field_y: StringProperty(name="Y field", default="y")
    field_z: StringProperty(name="Z field", default="z")
    field_type: StringProperty(name="Type field", default="type")
    use_local_coords: BoolProperty(name="Use local coordinates", default=False)

    def execute(self, context):
        path = self.filepath
        objects = context.selected_objects
        if not objects:
            self.report({'WARNING'}, "No objects selected for export.")
            return {'CANCELLED'}

        try:
            with open(path, 'w', newline='', encoding='utf-8') as csvfile:
                writer = csv.writer(csvfile, delimiter=self.delimiter)
                if self.include_header:
                    writer.writerow([self.field_name, self.field_x, self.field_y, self.field_z, self.field_type])
                for obj in objects:
                    if self.use_local_coords:
                        loc = obj.location
                    else:
                        loc = obj.matrix_world.to_translation()
                    name = obj.name
                    typ = obj.get("openbve_type", "")  # optional custom property
                    writer.writerow([name, loc.x, loc.y, loc.z, typ])
        except Exception as e:
            self.report({'ERROR'}, f"Error writing CSV: {e}")
            return {'CANCELLED'}

        self.report({'INFO'}, f"Exported {len(objects)} objects to {path}")
        return {'FINISHED'}


def menu_import(self, context):
    self.layout.operator(ImportOpenBVECSV.bl_idname, text="OpenBVE / Generic CSV (.csv)")


def menu_export(self, context):
    self.layout.operator(ExportOpenBVECSV.bl_idname, text="OpenBVE / Generic CSV (.csv)")


classes = (
    ImportOpenBVECSV,
    ExportOpenBVECSV,
)


def register():
    for c in classes:
        bpy.utils.register_class(c)
    bpy.types.TOPBAR_MT_file_import.append(menu_import)
    bpy.types.TOPBAR_MT_file_export.append(menu_export)


def unregister():
    for c in classes:
        bpy.utils.unregister_class(c)
    bpy.types.TOPBAR_MT_file_import.remove(menu_import)
    bpy.types.TOPBAR_MT_file_export.remove(menu_export)


if __name__ == "__main__":
    register()
